// <auto-generated />
namespace PocetKsPaleta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Adress20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adress20));
        
        string IMigrationMetadata.Id
        {
            get { return "201908230655044_Adress2.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
